# Generated by Django 4.1.6 on 2023-03-07 12:28

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_rename_likes_post_likecount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, db_index=True, max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='likecount',
            field=models.IntegerField(blank=True, db_index=True, default=0, null=True, verbose_name='Likes'),
        ),
    ]
